/**
 * GetOutcomesOverview handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: outcomes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getOutcomesOverview } from "@autara/api-server/domains/outcomes/handlers";
import type { OutcomesDDDDependencies } from "@autara/api-server/domains/outcomes";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@autara/tests/shared";
import { OUTCOMES_USE_CASES } from "../__factories__/use-cases.js";

describe("GetOutcomesOverview", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: OutcomesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<OutcomesDDDDependencies>(
      OUTCOMES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetOutcomesOverview, "execute").mockResolvedValue(useCaseResult);

    await getOutcomesOverview(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetOutcomesOverview.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
