/**
 * GetFinancialAccount handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: accounts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getFinancialAccount } from "@autara/api-server/domains/accounts/handlers";
import type { AccountsDDDDependencies } from "@autara/api-server/domains/accounts";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@autara/tests/shared";
import { ACCOUNTS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetFinancialAccount", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: AccountsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<AccountsDDDDependencies>(
      ACCOUNTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetFinancialAccount, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { accountId: entity.id };

    await getFinancialAccount(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetFinancialAccount.execute).toHaveBeenCalledWith(expect.objectContaining({ accountId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { accountId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetFinancialAccount, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getFinancialAccount(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
