/**
 * Dependency Container
 *
 * AUTO-GENERATED by codegen (api_server_domain_dependencies). Do not edit by hand.
 * Regenerate with: pnpm run codegen (domain list from platform/api-server/src/domains rescan).
 *
 * Manages dependency creation and caching per domain.
 */

import type { AdapterDynamoDBClient } from "@autara/adapters";
import { getDynamoClientInstance } from "../lib/dependencies/domain-dependencies.js";
import { executionContextService } from "../lib/context/execution-context.service.js";
import {
  buildAccountsDomainModule,
  buildActionsDomainModule,
  buildComplaintsDomainModule,
  buildExplanationsDomainModule,
  buildGoalsDomainModule,
  buildGovernanceDomainModule,
  buildIdentityDomainModule,
  buildOutcomesDomainModule,
  buildProposalsDomainModule,
} from "../domains/index.js";
import type {
  AccountsDomainModule,
  ActionsDomainModule,
  ComplaintsDomainModule,
  ExplanationsDomainModule,
  GoalsDomainModule,
  GovernanceDomainModule,
  IdentityDomainModule,
  OutcomesDomainModule,
  ProposalsDomainModule,
} from "../domains/index.js";

class DependencyContainer {
  private readonly dynamoClient: AdapterDynamoDBClient;

  private accountsModule: AccountsDomainModule | null = null;
  private actionsModule: ActionsDomainModule | null = null;
  private complaintsModule: ComplaintsDomainModule | null = null;
  private explanationsModule: ExplanationsDomainModule | null = null;
  private goalsModule: GoalsDomainModule | null = null;
  private governanceModule: GovernanceDomainModule | null = null;
  private identityModule: IdentityDomainModule | null = null;
  private outcomesModule: OutcomesDomainModule | null = null;
  private proposalsModule: ProposalsDomainModule | null = null;

  constructor(dynamoClient: AdapterDynamoDBClient) {
    this.dynamoClient = dynamoClient;
  }

  /**
   * Get accounts domain module
   */
  getAccountsDependencies(): AccountsDomainModule {
    if (!this.accountsModule) {
      this.accountsModule = buildAccountsDomainModule(this.dynamoClient);
    }
    return this.accountsModule;
  }

  /**
   * Get actions domain module
   */
  getActionsDependencies(): ActionsDomainModule {
    if (!this.actionsModule) {
      this.actionsModule = buildActionsDomainModule(this.dynamoClient);
    }
    return this.actionsModule;
  }

  /**
   * Get complaints domain module
   */
  getComplaintsDependencies(): ComplaintsDomainModule {
    if (!this.complaintsModule) {
      this.complaintsModule = buildComplaintsDomainModule(this.dynamoClient);
    }
    return this.complaintsModule;
  }

  /**
   * Get explanations domain module
   */
  getExplanationsDependencies(): ExplanationsDomainModule {
    if (!this.explanationsModule) {
      this.explanationsModule = buildExplanationsDomainModule(this.dynamoClient);
    }
    return this.explanationsModule;
  }

  /**
   * Get goals domain module
   */
  getGoalsDependencies(): GoalsDomainModule {
    if (!this.goalsModule) {
      this.goalsModule = buildGoalsDomainModule(this.dynamoClient);
    }
    return this.goalsModule;
  }

  /**
   * Get governance domain module
   */
  getGovernanceDependencies(): GovernanceDomainModule {
    if (!this.governanceModule) {
      this.governanceModule = buildGovernanceDomainModule(this.dynamoClient);
    }
    return this.governanceModule;
  }

  /**
   * Get identity domain module
   */
  getIdentityDependencies(): IdentityDomainModule {
    if (!this.identityModule) {
      this.identityModule = buildIdentityDomainModule(this.dynamoClient);
    }
    return this.identityModule;
  }

  /**
   * Get outcomes domain module
   */
  getOutcomesDependencies(): OutcomesDomainModule {
    if (!this.outcomesModule) {
      this.outcomesModule = buildOutcomesDomainModule(this.dynamoClient);
    }
    return this.outcomesModule;
  }

  /**
   * Get proposals domain module
   */
  getProposalsDependencies(): ProposalsDomainModule {
    if (!this.proposalsModule) {
      this.proposalsModule = buildProposalsDomainModule(this.dynamoClient);
    }
    return this.proposalsModule;
  }

  clearAccountsDependencies(): void { this.accountsModule = null; }
  clearActionsDependencies(): void { this.actionsModule = null; }
  clearComplaintsDependencies(): void { this.complaintsModule = null; }
  clearExplanationsDependencies(): void { this.explanationsModule = null; }
  clearGoalsDependencies(): void { this.goalsModule = null; }
  clearGovernanceDependencies(): void { this.governanceModule = null; }
  clearIdentityDependencies(): void { this.identityModule = null; }
  clearOutcomesDependencies(): void { this.outcomesModule = null; }
  clearProposalsDependencies(): void { this.proposalsModule = null; }

  getAccountsDependenciesForRequest(): AccountsDomainModule {
    return this.getAccountsDependencies();
  }

  getActionsDependenciesForRequest(): ActionsDomainModule {
    return this.getActionsDependencies();
  }

  getComplaintsDependenciesForRequest(): ComplaintsDomainModule {
    return this.getComplaintsDependencies();
  }

  getExplanationsDependenciesForRequest(): ExplanationsDomainModule {
    return this.getExplanationsDependencies();
  }

  getGoalsDependenciesForRequest(): GoalsDomainModule {
    return this.getGoalsDependencies();
  }

  getGovernanceDependenciesForRequest(): GovernanceDomainModule {
    return this.getGovernanceDependencies();
  }

  getIdentityDependenciesForRequest(): IdentityDomainModule {
    return this.getIdentityDependencies();
  }

  getOutcomesDependenciesForRequest(): OutcomesDomainModule {
    return this.getOutcomesDependencies();
  }

  getProposalsDependenciesForRequest(): ProposalsDomainModule {
    return this.getProposalsDependencies();
  }

  /**
   * Clear all caches
   */
  clearAllCaches(): void {
    this.accountsModule = null;
    this.actionsModule = null;
    this.complaintsModule = null;
    this.explanationsModule = null;
    this.goalsModule = null;
    this.governanceModule = null;
    this.identityModule = null;
    this.outcomesModule = null;
    this.proposalsModule = null;
  }
}

let dependencyContainerInstance: DependencyContainer | null = null;

export function getDependencyContainer(): DependencyContainer {
  if (!dependencyContainerInstance) {
    const dynamoClient = getDynamoClientInstance();
    dependencyContainerInstance = new DependencyContainer(dynamoClient);
  }
  return dependencyContainerInstance;
}
