/**
 * GoalRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: goals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * GoalRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements GoalRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  GoalRepository,
} from "@autara/services/goals";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { GoalRepositoryDdb } from "./goal-repository.ddb.js";

/**
 * GoalRepositoryAdapter
 *
 * Implements GoalRepository port for infrastructure layer.
 */
export class GoalRepositoryAdapter implements GoalRepository {
  private readonly ddb: GoalRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new GoalRepositoryDdb(this.dynamoClient);
  }

  async listGoals(input: Parameters<GoalRepository['listGoals']>[0]): Promise<Awaited<ReturnType<GoalRepository['listGoals']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listGoals(input);
  }

  async createGoal(input: Parameters<GoalRepository['createGoal']>[0]): Promise<Awaited<ReturnType<GoalRepository['createGoal']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createGoal(input);
  }

  async getGoal(input: Parameters<GoalRepository['getGoal']>[0]): Promise<Awaited<ReturnType<GoalRepository['getGoal']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getGoal(input);
  }
}
