/**
 * ComplaintRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: complaints
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ComplaintRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ComplaintRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ComplaintRepository,
} from "@autara/services/complaints";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ComplaintRepositoryDdb } from "./complaint-repository.ddb.js";

/**
 * ComplaintRepositoryAdapter
 *
 * Implements ComplaintRepository port for infrastructure layer.
 */
export class ComplaintRepositoryAdapter implements ComplaintRepository {
  private readonly ddb: ComplaintRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ComplaintRepositoryDdb(this.dynamoClient);
  }

  async listComplaintCases(input: Parameters<ComplaintRepository['listComplaintCases']>[0]): Promise<Awaited<ReturnType<ComplaintRepository['listComplaintCases']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listComplaintCases(input);
  }

  async openComplaintCase(input: Parameters<ComplaintRepository['openComplaintCase']>[0]): Promise<Awaited<ReturnType<ComplaintRepository['openComplaintCase']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.openComplaintCase(input);
  }

  async getComplaintCase(input: Parameters<ComplaintRepository['getComplaintCase']>[0]): Promise<Awaited<ReturnType<ComplaintRepository['getComplaintCase']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getComplaintCase(input);
  }
}
