/**
 * ProductOfferRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: accounts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ProductOfferRepository Port
 *
 * DDD: Application port for productofferrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListProductOffersInput, ListProductOffersOutput } from "../dto/product-offer.dto";
export interface ProductOfferRepository {
  listProductOffers(input: ListProductOffersInput): Promise<ListProductOffersOutput>;
}

export type { ListProductOffersInput, ListProductOffersOutput } from "../dto/product-offer.dto";
