/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: outcomes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Outcomes Domain Use Cases
 * 
 * List of all use case names for the outcomes domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const OUTCOMES_USE_CASES = [
  "executeGetOutcomeReport",
  "executeGetOutcomesOverview"
] as const;
