/**
 * Repository interface for ProductOffer
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: accounts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ProductOfferEntity
} from "../models/product-offer.entity.js";
import type {
  ListProductOffersParams
} from "../types/index.js";
/**
 * ProductOfferRepository Interface
 */
export interface ProductOfferRepository extends ReadRepository<ProductOfferEntity, string, ListProductOffersParams> {

}
