/**
 * Routes for Outcome
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: outcomes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getOutcomeReport } from "../handlers/outcome.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function outcomeRoutes(fastify: FastifyInstance) {
  // GET /v1/customers/{customerId}/outcomes (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/customers/:customerId/outcomes",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { customerId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getOutcomesDependenciesForRequest();
        await getOutcomeReport(request, reply, deps);
      });
    }
  );


}
