/**
 * Handlers for Outcome
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: outcomes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { OutcomesDomainModule } from "../dependencies/outcomes-ddd.dependencies.js";
import type { GetOutcomeReportInput } from "@autara/services/outcomes";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/customers/{customerId}/outcomes
 * Operation: getOutcomeReport
 */
export async function getOutcomeReport(
  request: FastifyRequest<{ Params: { customerId: string }; Querystring: { period?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: OutcomesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetOutcomeReportInput = {
    customerId: request.params.customerId,
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.outcomes.get.execute(input);
  return reply.code(200).send(result);
}


