/**
 * Handlers for Automation
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: actions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ActionsDomainModule } from "../dependencies/actions-ddd.dependencies.js";
import type { GetAutomationProfileInput } from "@autara/services/actions";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/customers/{customerId}/automation
 * Operation: getAutomationProfile
 */
export async function getAutomationProfile(
  request: FastifyRequest<{ Params: { customerId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ActionsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetAutomationProfileInput = {
    customerId: request.params.customerId,
  };
  const result = await deps.useCases.automations.get.execute(input);
  return reply.code(200).send(result);
}


