/**
 * Handlers for Reverse
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: actions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ActionsDomainModule } from "../dependencies/actions-ddd.dependencies.js";
import type { ReverseExecutedActionInput } from "@autara/services/actions";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/actions/{actionId}/reverse
 * Operation: reverseExecutedAction
 */
export async function reverseExecutedAction(
  request: FastifyRequest<{ Params: { actionId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ActionsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ReverseExecutedActionInput = {
    actionId: request.params.actionId,
  };
  const result = await deps.useCases.reverses.get.execute(input);
  return reply.code(200).send(result);
}


