/**
 * AccountRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: accounts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AccountRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements AccountRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  AccountRepository,
} from "@autara/services/accounts";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { AccountRepositoryDdb } from "./account-repository.ddb.js";

/**
 * AccountRepositoryAdapter
 *
 * Implements AccountRepository port for infrastructure layer.
 */
export class AccountRepositoryAdapter implements AccountRepository {
  private readonly ddb: AccountRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new AccountRepositoryDdb(this.dynamoClient);
  }

  async listFinancialAccounts(input: Parameters<AccountRepository['listFinancialAccounts']>[0]): Promise<Awaited<ReturnType<AccountRepository['listFinancialAccounts']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listFinancialAccounts(input);
  }

  async getFinancialAccount(input: Parameters<AccountRepository['getFinancialAccount']>[0]): Promise<Awaited<ReturnType<AccountRepository['getFinancialAccount']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getFinancialAccount(input);
  }
}
