/**
 * AccountRepository - DynamoDB Implementation
 *
 * Generated by DynamoDB Repository Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: accounts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AccountRepositoryDdb
 *
 * DDD: Infrastructure adapter for Account repository.
 * ⚠️  Missing x-dynamodb metadata - implementation not generated.
 */

import type { AccountRepository } from "@autara/services/accounts";

export class AccountRepositoryDdb implements AccountRepository {
  constructor(private readonly dynamoClient: any) {}

  async listFinancialAccounts(input: Parameters<AccountRepository['listFinancialAccounts']>[0]): Promise<Awaited<ReturnType<AccountRepository['listFinancialAccounts']>>> {
    // TODO: Implement using x-dynamodb metadata
    throw new Error("Not implemented - missing x-dynamodb metadata");
  }

  async getFinancialAccount(input: Parameters<AccountRepository['getFinancialAccount']>[0]): Promise<Awaited<ReturnType<AccountRepository['getFinancialAccount']>>> {
    // TODO: Implement using x-dynamodb metadata
    throw new Error("Not implemented - missing x-dynamodb metadata");
  }
}
