/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: accounts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./account-repository.ddb.js";
export * from "./product-offer-repository.ddb.js";
export * from "./account-repository.adapter.js";
export * from "./product-offer-repository.adapter.js";
