/**
 * Outcomes DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: outcomes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Outcomes Domain Module - Composition root
 *
 * DDD: Composition root for outcomes domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  OutcomeRepositoryAdapter,
  OverviewRepositoryAdapter,
} from "@autara/adapters/outcomes";
import { getIdGeneratorService } from "@autara/adapters";
import type { AdapterDynamoDBClient } from "@autara/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetOutcomeReport,
  ExecuteGetOutcomesOverview,
} from "@autara/services/outcomes/usecases";
// Ports (interfaces)
import type {
  OutcomeRepository,
  OverviewRepository,
} from "@autara/services/outcomes/ports";

export interface OutcomesDomainModule {
  repos: {
    outcomes: OutcomeRepository;
    overviews: OverviewRepository;
  };
  useCases: {
    outcomes: {
      get: ExecuteGetOutcomeReport;
    };
    overviews: {
      get: ExecuteGetOutcomesOverview;
    };
  };
}

export function buildOutcomesDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): OutcomesDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      outcomes?: OutcomeRepository;
      overviews?: OverviewRepository;
    } = {};

    obj.outcomes = new OutcomeRepositoryAdapter(dynamoClient);
    obj.overviews = new OverviewRepositoryAdapter(dynamoClient);
    return {
      outcomes: obj.outcomes!,
      overviews: obj.overviews!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    outcomes: {
      get: new ExecuteGetOutcomeReport(executionContext, idGenerator, repos.outcomes),
    },
    overviews: {
      get: new ExecuteGetOutcomesOverview(executionContext, idGenerator, repos.overviews),
    },
  };
  return { repos, useCases: useCases as OutcomesDomainModule["useCases"] };
}
