/**
 * GetOutcome DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: outcomes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetOutcomeReportParams } from "@autara/core/outcomes";

export function createGetOutcomeRequest(overrides: Partial<GetOutcomeReportParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
