/**
 * GetExplanation DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: explanations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetExplanationRecordParams } from "@autara/core/explanations";

export function createGetExplanationRequest(overrides: Partial<GetExplanationRecordParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
