/**
 * GetOutcomeReport handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: outcomes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getOutcomeReport } from "@autara/api-server/domains/outcomes/handlers";
import type { OutcomesDDDDependencies } from "@autara/api-server/domains/outcomes";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@autara/tests/shared";
import { OUTCOMES_USE_CASES } from "../__factories__/use-cases.js";

describe("GetOutcomeReport", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: OutcomesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<OutcomesDDDDependencies>(
      OUTCOMES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetOutcomeReport, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { customerId: entity.id };

    await getOutcomeReport(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetOutcomeReport.execute).toHaveBeenCalledWith(expect.objectContaining({ customerId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { customerId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetOutcomeReport, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getOutcomeReport(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
