/**
 * Routes for Explanation
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: explanations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getExplanationRecord, listExplanationRecords } from "../handlers/explanation.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function explanationRoutes(fastify: FastifyInstance) {
  // GET /v1/explanations (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/explanations",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getExplanationsDependenciesForRequest();
        await listExplanationRecords(request, reply, deps);
      });
    }
  );


  // GET /v1/explanations/{explanationId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/explanations/:explanationId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { explanationId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getExplanationsDependenciesForRequest();
        await getExplanationRecord(request, reply, deps);
      });
    }
  );


}
