/**
 * Domain routes – register all domain route modules.
 *
 * AUTO-GENERATED by codegen (api_server_domain_routes). Do not edit by hand.
 * Rescans platform/api-server/src/domains and includes only domains that have
 * routes/index.ts and dependencies/{domain}-ddd.dependencies.ts.
 * Extension excludes/imports from x-codegen.api-server.extensions in OpenAPI YAML.
 */

import type { FastifyInstance } from "fastify";
import { registerDomainFromModule } from "./route-registration.js";

// Static imports so the bundle includes all domain route modules
import * as accountsRoutes from "../../domains/accounts/routes/index.js";
import * as actionsRoutes from "../../domains/actions/routes/index.js";
import * as complaintsRoutes from "../../domains/complaints/routes/index.js";
import * as explanationsRoutes from "../../domains/explanations/routes/index.js";
import * as goalsRoutes from "../../domains/goals/routes/index.js";
import * as governanceRoutes from "../../domains/governance/routes/index.js";
import * as identityRoutes from "../../domains/identity/routes/index.js";
import * as outcomesRoutes from "../../domains/outcomes/routes/index.js";
import * as proposalsRoutes from "../../domains/proposals/routes/index.js";

const DOMAIN_MODULES: Array<{
  domain: string;
  mod: Record<string, unknown>;
  exclude?: string[];
}> = [
  { domain: "accounts", mod: accountsRoutes },
  { domain: "actions", mod: actionsRoutes },
  { domain: "complaints", mod: complaintsRoutes },
  { domain: "explanations", mod: explanationsRoutes },
  { domain: "goals", mod: goalsRoutes },
  { domain: "governance", mod: governanceRoutes },
  {
    domain: "identity",
    mod: identityRoutes,
    exclude: [
      "authRoutes",
      "signupRoutes",
      "sessionRoutes",
      "tokenRoutes",
      "profileRoutes",
    ],
  },
  { domain: "outcomes", mod: outcomesRoutes },
  { domain: "proposals", mod: proposalsRoutes },
];

export async function registerAllDomainRoutes(
  fastify: FastifyInstance,
): Promise<void> {
  console.log("[DEBUG] Registering domain routes...");
  try {
    for (const { domain, mod, exclude } of DOMAIN_MODULES) {
      await registerDomainFromModule(fastify, domain, mod, exclude ?? []);
    }
    console.log("[DEBUG] ✅ All domain routes registered");
  } catch (error: unknown) {
    const err = error instanceof Error ? error : new Error(String(error));
    console.error("[DEBUG] ❌ Error registering domain routes:", err.message);
    if (err.stack) console.error(err.stack);
    throw error;
  }
}
