/**
 * ModelVersion Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/governance.openapi.types.js";
import { schemas } from "../schemas/governance.schemas.js";

/**
 * Entity: ModelVersionEntity
 * Description: Represents the ModelVersion domain model.
 * Source: schemas.ModelVersion
 * Type: Domain Entity (API)
 */
export const ModelVersionEntitySchema = schemas.ModelVersion;
export type ModelVersionEntity = components["schemas"]["ModelVersion"];
