/**
 * ResumeAutomation handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: actions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { resumeAutomation } from "@autara/api-server/domains/actions/handlers";
import type { ActionsDDDDependencies } from "@autara/api-server/domains/actions";
import { createCreateResumeRequest } from "@autara/factories/actions";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@autara/tests/shared";
import { ACTIONS_USE_CASES } from "../__factories__/use-cases.js";

describe("ResumeAutomation", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ActionsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ActionsDDDDependencies>(
      ACTIONS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = createCreateResumeRequest();
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeResumeAutomation, "execute").mockResolvedValue(useCaseResult);

    await resumeAutomation(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeResumeAutomation.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
