/**
 * Handlers for Proposal
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: proposals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ProposalsDomainModule } from "../dependencies/proposals-ddd.dependencies.js";
import type { CreateActionProposalInput, GetActionProposalInput, ListActionProposalsInput } from "@autara/services/proposals";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/proposals
 * Operation: listActionProposals
 */
export async function listActionProposals(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], status?: string | string[], material?: string | string[], customerId?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: ProposalsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListActionProposalsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.proposals.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/proposals
 * Operation: createActionProposal
 */
export async function createActionProposal(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: ProposalsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateActionProposalInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.proposals.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/proposals/{proposalId}
 * Operation: getActionProposal
 */
export async function getActionProposal(
  request: FastifyRequest<{ Params: { proposalId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ProposalsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetActionProposalInput = {
    proposalId: request.params.proposalId,
  };
  const result = await deps.useCases.proposals.get.execute(input);
  return reply.code(200).send(result);
}


