/**
 * Approve DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Approve DTOs
 *
 * DDD: Application DTOs for Approve use cases.
 */

import type { ApproveModelVersionParams } from "@autara/core/governance/types";

export type ApproveModelVersionInput = ApproveModelVersionParams;

export type ApproveModelVersionOutput = {};
