/**
 * KillSwitch DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * KillSwitch DTOs
 *
 * DDD: Application DTOs for KillSwitch use cases.
 */

import type { TriggerVendorKillSwitchParams } from "@autara/core/governance/types";

export type TriggerVendorKillSwitchInput = TriggerVendorKillSwitchParams;

export type TriggerVendorKillSwitchOutput = {};
