/**
 * Vendor DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Vendor DTOs
 *
 * DDD: Application DTOs for Vendor use cases.
 */

import type { ListVendorDependenciesParams } from "@autara/core/governance/types";

export type ListVendorDependenciesInput = ListVendorDependenciesParams;

export type ListVendorDependenciesOutput = {};
