/**
 * ProductOffer Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: accounts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/accounts.openapi.types.js";
import { schemas } from "../schemas/accounts.schemas.js";

/**
 * Entity: ProductOfferEntity
 * Description: Represents the ProductOffer domain model.
 * Source: schemas.ProductOffer
 * Type: Domain Entity (API)
 */
export const ProductOfferEntitySchema = schemas.ProductOffer;
export type ProductOfferEntity = components["schemas"]["ProductOffer"];
