/**
 * ProductOffer Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: accounts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { ProductOfferEntity } from "@autara/core/accounts/models/index.js";
import { accountsSchemas } from "@autara/core/accounts";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "acc";

export function createProductOffer(overrides: Partial<ProductOfferEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    headlineRate: overrides.headlineRate ?? faker.number.int(),
    hostInstitutionProduct: overrides.hostInstitutionProduct ?? faker.datatype.boolean(),
    offerId: overrides.offerId ?? `ofr_${ulid().toLowerCase()}`,
    productType: overrides.productType ?? faker.lorem.word(),
    provider: overrides.provider ?? faker.lorem.word(),
    ...overrides,
  };

  return accountsSchemas.ProductOffer.parse(raw);
}

export function productOfferBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createProductOffer(overrides));
}
