/**
 * Governance DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Governance Domain Module - Composition root
 *
 * DDD: Composition root for governance domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ApproveRepositoryAdapter,
  FairnessRepositoryAdapter,
  KillSwitchRepositoryAdapter,
  ModelVersionRepositoryAdapter,
  RollbackRepositoryAdapter,
  VendorRepositoryAdapter,
} from "@autara/adapters/governance";
import { getIdGeneratorService } from "@autara/adapters";
import type { AdapterDynamoDBClient } from "@autara/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteApproveModelVersion,
  ExecuteGetFairnessMonitoring,
  ExecuteListModelVersions,
  ExecuteListVendorDependencies,
  ExecuteRegisterModelVersion,
  ExecuteRollbackModelVersion,
  ExecuteTriggerVendorKillSwitch,
} from "@autara/services/governance/usecases";
// Ports (interfaces)
import type {
  ApproveRepository,
  FairnessRepository,
  KillSwitchRepository,
  ModelVersionRepository,
  RollbackRepository,
  VendorRepository,
} from "@autara/services/governance/ports";

export interface GovernanceDomainModule {
  repos: {
    approves: ApproveRepository;
    fairnesses: FairnessRepository;
    killSwitches: KillSwitchRepository;
    modelVersions: ModelVersionRepository;
    rollbacks: RollbackRepository;
    vendors: VendorRepository;
  };
  useCases: {
    approves: {
      create: ExecuteApproveModelVersion;
    };
    fairnesses: {
      get: ExecuteGetFairnessMonitoring;
    };
    killSwitches: {
      create: ExecuteTriggerVendorKillSwitch;
    };
    modelVersions: {
      create: ExecuteRegisterModelVersion;
      list: ExecuteListModelVersions;
    };
    rollbacks: {
      get: ExecuteRollbackModelVersion;
    };
    vendors: {
      list: ExecuteListVendorDependencies;
    };
  };
}

export function buildGovernanceDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): GovernanceDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      approves?: ApproveRepository;
      fairnesses?: FairnessRepository;
      killSwitches?: KillSwitchRepository;
      modelVersions?: ModelVersionRepository;
      rollbacks?: RollbackRepository;
      vendors?: VendorRepository;
    } = {};

    obj.approves = new ApproveRepositoryAdapter(dynamoClient);
    obj.fairnesses = new FairnessRepositoryAdapter(dynamoClient);
    obj.killSwitches = new KillSwitchRepositoryAdapter(dynamoClient);
    obj.modelVersions = new ModelVersionRepositoryAdapter(dynamoClient);
    obj.rollbacks = new RollbackRepositoryAdapter(dynamoClient);
    obj.vendors = new VendorRepositoryAdapter(dynamoClient);
    return {
      approves: obj.approves!,
      fairnesses: obj.fairnesses!,
      killSwitches: obj.killSwitches!,
      modelVersions: obj.modelVersions!,
      rollbacks: obj.rollbacks!,
      vendors: obj.vendors!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    approves: {
      create: new ExecuteApproveModelVersion(executionContext, idGenerator, repos.approves),
    },
    fairnesses: {
      get: new ExecuteGetFairnessMonitoring(executionContext, idGenerator, repos.fairnesses),
    },
    killSwitches: {
      create: new ExecuteTriggerVendorKillSwitch(executionContext, idGenerator, repos.killSwitches),
    },
    modelVersions: {
      create: new ExecuteRegisterModelVersion(executionContext, idGenerator, repos.modelVersions),
      list: new ExecuteListModelVersions(executionContext, idGenerator, repos.modelVersions),
    },
    rollbacks: {
      get: new ExecuteRollbackModelVersion(executionContext, idGenerator, repos.rollbacks),
    },
    vendors: {
      list: new ExecuteListVendorDependencies(executionContext, idGenerator, repos.vendors),
    },
  };
  return { repos, useCases: useCases as GovernanceDomainModule["useCases"] };
}
