/**
 * Action DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: actions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Action DTOs
 *
 * DDD: Application DTOs for Action use cases.
 */

import type { GetExecutedActionParams, ListExecutedActionsParams } from "@autara/core/actions/types";

export type ListExecutedActionsInput = ListExecutedActionsParams;

export type GetExecutedActionInput = GetExecutedActionParams;

export type ListExecutedActionsOutput = {};

export type GetExecutedActionOutput = {};
