/**
 * Pause DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: actions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Pause DTOs
 *
 * DDD: Application DTOs for Pause use cases.
 */

import type { PauseAutomationParams, PauseAutomationRequestInput } from "@autara/core/actions/types";

export type PauseAutomationInput = PauseAutomationParams & PauseAutomationRequestInput;

export type PauseAutomationOutput = {};
