/**
 * Reverse DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: actions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Reverse DTOs
 *
 * DDD: Application DTOs for Reverse use cases.
 */

import type { ReverseExecutedActionParams } from "@autara/core/actions/types";

export type ReverseExecutedActionInput = ReverseExecutedActionParams;

export type ReverseExecutedActionOutput = {};
