/**
 * Test utilities barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: explanations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Explanations Service Test Utilities
 *
 * Barrel export for factories, mock repositories, and test helpers.
 * Import these in explanations service tests for consistent mocking.
 */

// Factories (entity and DTO factories) - use barrel export
// No factories generated

// Mock repositories are not needed - use createMockDependencies from @autara/tests/shared
// export * from "./mocks/index.js";

// Test setup helpers (now in shared, but keeping for backward compatibility)
export {
  TEST_JWT_SECRET,
  TEST_ORG_ID,
  TEST_ACCOUNT_ID,
  TEST_USER_EMAIL,
  generateAuthToken,
  parseJsonResponse,
} from "@autara/tests/shared";
