/**
 * KillSwitchRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * KillSwitchRepository Port
 *
 * DDD: Application port for killswitchrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { TriggerVendorKillSwitchInput, TriggerVendorKillSwitchOutput } from "../dto/kill-switch.dto";
export interface KillSwitchRepository {
  triggerVendorKillSwitch(input: TriggerVendorKillSwitchInput): Promise<TriggerVendorKillSwitchOutput>;
}

export type { TriggerVendorKillSwitchInput, TriggerVendorKillSwitchOutput } from "../dto/kill-switch.dto";
