/**
 * GetAutomationProfile handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: actions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getAutomationProfile } from "@autara/api-server/domains/actions/handlers";
import type { ActionsDDDDependencies } from "@autara/api-server/domains/actions";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@autara/tests/shared";
import { ACTIONS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetAutomationProfile", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ActionsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ActionsDDDDependencies>(
      ACTIONS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetAutomationProfile, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { customerId: entity.id };

    await getAutomationProfile(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetAutomationProfile.execute).toHaveBeenCalledWith(expect.objectContaining({ customerId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { customerId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetAutomationProfile, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getAutomationProfile(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
