/**
 * ExecuteListVendorDependencies - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListVendorDependencies Use Case
 *
 * DDD: Application use case for list Vendor.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListVendorDependenciesInput, ListVendorDependenciesOutput } from "../dto/vendor.dto";
import type { ExecutionContextService, IdGeneratorService } from "@autara/services/_shared/index.js";
import type { VendorRepository } from "../ports";

export class ExecuteListVendorDependencies {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly vendor: VendorRepository
  ) {}

  async execute(input: ListVendorDependenciesInput): Promise<ListVendorDependenciesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.gvnId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.vendor.listVendorDependencies({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListVendorDependenciesOutput;
  }
}
