/**
 * ExecuteRegisterModelVersion - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteRegisterModelVersion Use Case
 *
 * DDD: Application use case for create ModelVersion.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { RegisterModelVersionInput, RegisterModelVersionOutput } from "../dto/model-version.dto";
import type { ExecutionContextService, IdGeneratorService } from "@autara/services/_shared/index.js";
import type { ModelVersionRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteRegisterModelVersion {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly modelVersion: ModelVersionRepository
  ) {}

  async execute(input: RegisterModelVersionInput): Promise<RegisterModelVersionOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.gvnId();

    // All field names extracted from OpenAPI spec: name, propensityNotes, version
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.version) {
      throw new ValidationError("version is required");
    }
    if (!input.name) {
      throw new ValidationError("name is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (governance domain)
    const entityId = this.idGenerator.gvnId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.modelVersion.registerModelVersion({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as RegisterModelVersionOutput;
  }
}
