/**
 * DeclineRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: proposals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DeclineRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements DeclineRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  DeclineRepository,
} from "@autara/services/proposals";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { DeclineRepositoryDdb } from "./decline-repository.ddb.js";

/**
 * DeclineRepositoryAdapter
 *
 * Implements DeclineRepository port for infrastructure layer.
 */
export class DeclineRepositoryAdapter implements DeclineRepository {
  private readonly ddb: DeclineRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new DeclineRepositoryDdb(this.dynamoClient);
  }

  async declineActionProposal(input: Parameters<DeclineRepository['declineActionProposal']>[0]): Promise<Awaited<ReturnType<DeclineRepository['declineActionProposal']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.declineActionProposal(input);
  }
}
