/**
 * ExceptionQueueRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: proposals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExceptionQueueRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ExceptionQueueRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ExceptionQueueRepository,
} from "@autara/services/proposals";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ExceptionQueueRepositoryDdb } from "./exception-queue-repository.ddb.js";

/**
 * ExceptionQueueRepositoryAdapter
 *
 * Implements ExceptionQueueRepository port for infrastructure layer.
 */
export class ExceptionQueueRepositoryAdapter implements ExceptionQueueRepository {
  private readonly ddb: ExceptionQueueRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ExceptionQueueRepositoryDdb(this.dynamoClient);
  }

  async listAdviserExceptions(input: Parameters<ExceptionQueueRepository['listAdviserExceptions']>[0]): Promise<Awaited<ReturnType<ExceptionQueueRepository['listAdviserExceptions']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listAdviserExceptions(input);
  }
}
