/**
 * Accounts DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: accounts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Accounts Domain Module - Composition root
 *
 * DDD: Composition root for accounts domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  AccountRepositoryAdapter,
  ProductOfferRepositoryAdapter,
} from "@autara/adapters/accounts";
import { getIdGeneratorService } from "@autara/adapters";
import type { AdapterDynamoDBClient } from "@autara/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetFinancialAccount,
  ExecuteListFinancialAccounts,
  ExecuteListProductOffers,
} from "@autara/services/accounts/usecases";
// Ports (interfaces)
import type {
  AccountRepository,
  ProductOfferRepository,
} from "@autara/services/accounts/ports";

export interface AccountsDomainModule {
  repos: {
    accounts: AccountRepository;
    productOffers: ProductOfferRepository;
  };
  useCases: {
    accounts: {
      get: ExecuteGetFinancialAccount;
      list: ExecuteListFinancialAccounts;
    };
    productOffers: {
      list: ExecuteListProductOffers;
    };
  };
}

export function buildAccountsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): AccountsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      accounts?: AccountRepository;
      productOffers?: ProductOfferRepository;
    } = {};

    obj.accounts = new AccountRepositoryAdapter(dynamoClient);
    obj.productOffers = new ProductOfferRepositoryAdapter(dynamoClient);
    return {
      accounts: obj.accounts!,
      productOffers: obj.productOffers!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    accounts: {
      get: new ExecuteGetFinancialAccount(executionContext, idGenerator, repos.accounts),
      list: new ExecuteListFinancialAccounts(executionContext, idGenerator, repos.accounts),
    },
    productOffers: {
      list: new ExecuteListProductOffers(executionContext, idGenerator, repos.productOffers),
    },
  };
  return { repos, useCases: useCases as AccountsDomainModule["useCases"] };
}
