/**
 * Routes for Account
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: accounts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getFinancialAccount, listFinancialAccounts } from "../handlers/account.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function accountRoutes(fastify: FastifyInstance) {
  // GET /v1/customers/{customerId}/accounts (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/customers/:customerId/accounts",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { customerId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAccountsDependenciesForRequest();
        await listFinancialAccounts(request, reply, deps);
      });
    }
  );


  // GET /v1/customers/{customerId}/accounts/{accountId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/customers/:customerId/accounts/:accountId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { customerId: string, accountId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAccountsDependenciesForRequest();
        await getFinancialAccount(request, reply, deps);
      });
    }
  );


}
