/**
 * Repository interface for Goal
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: goals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  GoalEntity
} from "../models/goal.entity.js";
import type {
  ListGoalsParams,
  Goal
} from "../types/index.js";
/**
 * GoalRepository Interface
 */
export interface GoalRepository extends CreateReadRepository<GoalEntity, Goal, string, ListGoalsParams> {

}
