/**
 * CreateDecline DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: proposals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { DeclineActionProposalParams } from "@autara/core/proposals";

export function createCreateDeclineRequest(overrides: Partial<DeclineActionProposalParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
