/**
 * ModelVersion Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { ModelVersionEntity } from "@autara/core/governance/models/index.js";
import { governanceSchemas } from "@autara/core/governance";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "gvn";

export function createModelVersion(overrides: Partial<ModelVersionEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    modelVersionId: overrides.modelVersionId ?? `gvn_${ulid().toLowerCase()}`,
    name: overrides.name ?? faker.person.fullName(),
    status: overrides.status ?? "draft",
    version: overrides.version ?? faker.lorem.word(),
    ...overrides,
  };

  return governanceSchemas.ModelVersion.parse(raw);
}

export function modelVersionBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createModelVersion(overrides));
}
