/**
 * Routes for Decline
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: proposals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { declineActionProposal } from "../handlers/decline.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function declineRoutes(fastify: FastifyInstance) {
  // POST /v1/proposals/{proposalId}/decline (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/proposals/:proposalId/decline",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { proposalId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getProposalsDependenciesForRequest();
        await declineActionProposal(request, reply, deps);
      });
    }
  );


}
