/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: proposals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { exceptionQueueRoutes } from "./exception-queue.routes.js";
export { confirmRoutes } from "./confirm.routes.js";
export { declineRoutes } from "./decline.routes.js";
export { proposalRoutes } from "./proposal.routes.js";
