/**
 * ExecuteDeclineActionProposal - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: proposals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteDeclineActionProposal Use Case
 *
 * DDD: Application use case for get Decline.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { DeclineActionProposalInput, DeclineActionProposalOutput } from "../dto/decline.dto";
import type { ExecutionContextService, IdGeneratorService } from "@autara/services/_shared/index.js";
import type { DeclineRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteDeclineActionProposal {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly decline: DeclineRepository
  ) {}

  async execute(input: DeclineActionProposalInput): Promise<DeclineActionProposalOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.prpId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).proposalId) {
      throw new ValidationError("proposalId is required");
    }
    const proposalId = (input as any).proposalId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.decline.declineActionProposal({ proposalId: proposalId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${proposalId}`);
    }

    return entity as DeclineActionProposalOutput;
  }
}
