/**
 * ExecuteListActionProposals - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: proposals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListActionProposals Use Case
 *
 * DDD: Application use case for list Proposal.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListActionProposalsInput, ListActionProposalsOutput } from "../dto/proposal.dto";
import type { ExecutionContextService, IdGeneratorService } from "@autara/services/_shared/index.js";
import type { ProposalRepository } from "../ports";

export class ExecuteListActionProposals {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly proposal: ProposalRepository
  ) {}

  async execute(input: ListActionProposalsInput): Promise<ListActionProposalsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.prpId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.proposal.listActionProposals({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListActionProposalsOutput;
  }
}
