/**
 * ExecuteConfirmActionProposal - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: proposals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteConfirmActionProposal Use Case
 *
 * DDD: Application use case for get Confirm.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ConfirmActionProposalInput, ConfirmActionProposalOutput } from "../dto/confirm.dto";
import type { ExecutionContextService, IdGeneratorService } from "@autara/services/_shared/index.js";
import type { ConfirmRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteConfirmActionProposal {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly confirm: ConfirmRepository
  ) {}

  async execute(input: ConfirmActionProposalInput): Promise<ConfirmActionProposalOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.prpId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).proposalId) {
      throw new ValidationError("proposalId is required");
    }
    const proposalId = (input as any).proposalId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.confirm.confirmActionProposal({ proposalId: proposalId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${proposalId}`);
    }

    return entity as ConfirmActionProposalOutput;
  }
}
