/**
 * ListAction DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: actions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListExecutedActionsParams } from "@autara/core/actions";

export function createListActionRequest(overrides: Partial<ListExecutedActionsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
