/**
 * Confirm DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: proposals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Confirm DTOs
 *
 * DDD: Application DTOs for Confirm use cases.
 */

import type { ConfirmActionProposalParams } from "@autara/core/proposals/types";

export type ConfirmActionProposalInput = ConfirmActionProposalParams;

export type ConfirmActionProposalOutput = {};
