/**
 * Proposal DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: proposals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Proposal DTOs
 *
 * DDD: Application DTOs for Proposal use cases.
 */

import type { CreateActionProposalRequestInput, GetActionProposalParams, ListActionProposalsParams } from "@autara/core/proposals/types";

export type ListActionProposalsInput = ListActionProposalsParams;

export type CreateActionProposalInput = CreateActionProposalRequestInput;

export type GetActionProposalInput = GetActionProposalParams;

export type ListActionProposalsOutput = {};

export type CreateActionProposalOutput = {};

export type GetActionProposalOutput = {};
