/**
 * Proposals Zod Schemas - Runtime validation schemas
 *
 * Generated by Zod Schemas Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: proposals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { makeApi, Zodios, type ZodiosOptions } from '@zodios/core';
import { z } from 'zod';

const createActionProposal_Body = z
  .object({
    customerId: z.string().regex(/^cst_[0-9A-HJKMNP-TV-Z]{26}$/),
    actionType: z.enum([
      'payBill',
      'savingsSweep',
      'refinance',
      'providerSwitch',
      'allocationChange',
    ]),
    material: z.boolean(),
    estimatedBenefit: z.number().optional(),
    policyId: z.string().optional(),
  })
  .passthrough();

export const schemas: any = {
  createActionProposal_Body,
};

const endpoints = makeApi([
  {
    method: 'get',
    path: '/v1/adviser/exception-queue',
    alias: 'listAdviserExceptions',
    requestFormat: 'json',
    parameters: [
      {
        name: 'cursor',
        type: 'Query',
        schema: z.string().optional(),
      },
      {
        name: 'limit',
        type: 'Query',
        schema: z.number().int().gte(1).lte(200).optional().default(50),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            items: z.array(
              z
                .object({
                  proposalId: z.string().regex(/^prp_[0-9A-HJKMNP-TV-Z]{26}$/),
                  customerId: z.string().regex(/^cst_[0-9A-HJKMNP-TV-Z]{26}$/),
                  actionType: z.enum([
                    'payBill',
                    'savingsSweep',
                    'refinance',
                    'providerSwitch',
                    'allocationChange',
                  ]),
                  status: z.enum([
                    'pending',
                    'confirmed',
                    'rejected',
                    'expired',
                    'escalated',
                  ]),
                  material: z.boolean(),
                  estimatedBenefit: z.number().optional(),
                  explanationId: z.string().optional(),
                  suitability: z
                    .object({
                      suitabilityCheckId: z
                        .string()
                        .regex(/^sut_[0-9A-HJKMNP-TV-Z]{26}$/),
                      customerId: z
                        .string()
                        .regex(/^cst_[0-9A-HJKMNP-TV-Z]{26}$/),
                      result: z.enum(['pass', 'fail', 'escalate']),
                      perimeter: z.string().optional(),
                      checkedAt: z.string().datetime({ offset: true }),
                    })
                    .passthrough()
                    .optional(),
                  hostInstitutionLosing: z.boolean().optional(),
                  createdAt: z.string().datetime({ offset: true }),
                  updatedAt: z.string().datetime({ offset: true }).optional(),
                })
                .passthrough()
            ),
            nextCursor: z.string().optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'get',
    path: '/v1/proposals',
    alias: 'listActionProposals',
    requestFormat: 'json',
    parameters: [
      {
        name: 'cursor',
        type: 'Query',
        schema: z.string().optional(),
      },
      {
        name: 'limit',
        type: 'Query',
        schema: z.number().int().gte(1).lte(200).optional().default(50),
      },
      {
        name: 'status',
        type: 'Query',
        schema: z
          .enum(['pending', 'confirmed', 'rejected', 'expired', 'escalated'])
          .optional(),
      },
      {
        name: 'material',
        type: 'Query',
        schema: z.boolean().optional(),
      },
      {
        name: 'customerId',
        type: 'Query',
        schema: z
          .string()
          .regex(/^cst_[0-9A-HJKMNP-TV-Z]{26}$/)
          .optional(),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            items: z.array(
              z
                .object({
                  proposalId: z.string().regex(/^prp_[0-9A-HJKMNP-TV-Z]{26}$/),
                  customerId: z.string().regex(/^cst_[0-9A-HJKMNP-TV-Z]{26}$/),
                  actionType: z.enum([
                    'payBill',
                    'savingsSweep',
                    'refinance',
                    'providerSwitch',
                    'allocationChange',
                  ]),
                  status: z.enum([
                    'pending',
                    'confirmed',
                    'rejected',
                    'expired',
                    'escalated',
                  ]),
                  material: z.boolean(),
                  estimatedBenefit: z.number().optional(),
                  explanationId: z.string().optional(),
                  suitability: z
                    .object({
                      suitabilityCheckId: z
                        .string()
                        .regex(/^sut_[0-9A-HJKMNP-TV-Z]{26}$/),
                      customerId: z
                        .string()
                        .regex(/^cst_[0-9A-HJKMNP-TV-Z]{26}$/),
                      result: z.enum(['pass', 'fail', 'escalate']),
                      perimeter: z.string().optional(),
                      checkedAt: z.string().datetime({ offset: true }),
                    })
                    .passthrough()
                    .optional(),
                  hostInstitutionLosing: z.boolean().optional(),
                  createdAt: z.string().datetime({ offset: true }),
                  updatedAt: z.string().datetime({ offset: true }).optional(),
                })
                .passthrough()
            ),
            nextCursor: z.string().optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/proposals',
    alias: 'createActionProposal',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: createActionProposal_Body,
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            proposalId: z.string().regex(/^prp_[0-9A-HJKMNP-TV-Z]{26}$/),
            customerId: z.string().regex(/^cst_[0-9A-HJKMNP-TV-Z]{26}$/),
            actionType: z.enum([
              'payBill',
              'savingsSweep',
              'refinance',
              'providerSwitch',
              'allocationChange',
            ]),
            status: z.enum([
              'pending',
              'confirmed',
              'rejected',
              'expired',
              'escalated',
            ]),
            material: z.boolean(),
            estimatedBenefit: z.number().optional(),
            explanationId: z.string().optional(),
            suitability: z
              .object({
                suitabilityCheckId: z
                  .string()
                  .regex(/^sut_[0-9A-HJKMNP-TV-Z]{26}$/),
                customerId: z.string().regex(/^cst_[0-9A-HJKMNP-TV-Z]{26}$/),
                result: z.enum(['pass', 'fail', 'escalate']),
                perimeter: z.string().optional(),
                checkedAt: z.string().datetime({ offset: true }),
              })
              .passthrough()
              .optional(),
            hostInstitutionLosing: z.boolean().optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }).optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'get',
    path: '/v1/proposals/:proposalId',
    alias: 'getActionProposal',
    requestFormat: 'json',
    parameters: [
      {
        name: 'proposalId',
        type: 'Path',
        schema: z.string().regex(/^prp_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            proposalId: z.string().regex(/^prp_[0-9A-HJKMNP-TV-Z]{26}$/),
            customerId: z.string().regex(/^cst_[0-9A-HJKMNP-TV-Z]{26}$/),
            actionType: z.enum([
              'payBill',
              'savingsSweep',
              'refinance',
              'providerSwitch',
              'allocationChange',
            ]),
            status: z.enum([
              'pending',
              'confirmed',
              'rejected',
              'expired',
              'escalated',
            ]),
            material: z.boolean(),
            estimatedBenefit: z.number().optional(),
            explanationId: z.string().optional(),
            suitability: z
              .object({
                suitabilityCheckId: z
                  .string()
                  .regex(/^sut_[0-9A-HJKMNP-TV-Z]{26}$/),
                customerId: z.string().regex(/^cst_[0-9A-HJKMNP-TV-Z]{26}$/),
                result: z.enum(['pass', 'fail', 'escalate']),
                perimeter: z.string().optional(),
                checkedAt: z.string().datetime({ offset: true }),
              })
              .passthrough()
              .optional(),
            hostInstitutionLosing: z.boolean().optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }).optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/proposals/:proposalId/confirm',
    alias: 'confirmActionProposal',
    requestFormat: 'json',
    parameters: [
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
      {
        name: 'proposalId',
        type: 'Path',
        schema: z.string().regex(/^prp_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            proposalId: z.string().regex(/^prp_[0-9A-HJKMNP-TV-Z]{26}$/),
            customerId: z.string().regex(/^cst_[0-9A-HJKMNP-TV-Z]{26}$/),
            actionType: z.enum([
              'payBill',
              'savingsSweep',
              'refinance',
              'providerSwitch',
              'allocationChange',
            ]),
            status: z.enum([
              'pending',
              'confirmed',
              'rejected',
              'expired',
              'escalated',
            ]),
            material: z.boolean(),
            estimatedBenefit: z.number().optional(),
            explanationId: z.string().optional(),
            suitability: z
              .object({
                suitabilityCheckId: z
                  .string()
                  .regex(/^sut_[0-9A-HJKMNP-TV-Z]{26}$/),
                customerId: z.string().regex(/^cst_[0-9A-HJKMNP-TV-Z]{26}$/),
                result: z.enum(['pass', 'fail', 'escalate']),
                perimeter: z.string().optional(),
                checkedAt: z.string().datetime({ offset: true }),
              })
              .passthrough()
              .optional(),
            hostInstitutionLosing: z.boolean().optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }).optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/proposals/:proposalId/decline',
    alias: 'declineActionProposal',
    requestFormat: 'json',
    parameters: [
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
      {
        name: 'proposalId',
        type: 'Path',
        schema: z.string().regex(/^prp_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            proposalId: z.string().regex(/^prp_[0-9A-HJKMNP-TV-Z]{26}$/),
            customerId: z.string().regex(/^cst_[0-9A-HJKMNP-TV-Z]{26}$/),
            actionType: z.enum([
              'payBill',
              'savingsSweep',
              'refinance',
              'providerSwitch',
              'allocationChange',
            ]),
            status: z.enum([
              'pending',
              'confirmed',
              'rejected',
              'expired',
              'escalated',
            ]),
            material: z.boolean(),
            estimatedBenefit: z.number().optional(),
            explanationId: z.string().optional(),
            suitability: z
              .object({
                suitabilityCheckId: z
                  .string()
                  .regex(/^sut_[0-9A-HJKMNP-TV-Z]{26}$/),
                customerId: z.string().regex(/^cst_[0-9A-HJKMNP-TV-Z]{26}$/),
                result: z.enum(['pass', 'fail', 'escalate']),
                perimeter: z.string().optional(),
                checkedAt: z.string().datetime({ offset: true }),
              })
              .passthrough()
              .optional(),
            hostInstitutionLosing: z.boolean().optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }).optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
]);

export const api: any = new Zodios(
  'https://api.ddd-codegen-starter.local',
  endpoints
);

export function createApiClient(baseUrl: string, options?: ZodiosOptions): any {
  return new Zodios(baseUrl, endpoints, options);
}
