/**
 * GetGoal handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: goals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getGoal } from "@autara/api-server/domains/goals/handlers";
import type { GoalsDDDDependencies } from "@autara/api-server/domains/goals";
import { createGoal as createGoalEntity } from "@autara/factories/goals";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@autara/tests/shared";
import { GOALS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetGoal", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: GoalsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<GoalsDDDDependencies>(
      GOALS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createGoalEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetGoal, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { goalId: entity.id };

    await getGoal(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetGoal.execute).toHaveBeenCalledWith(expect.objectContaining({ goalId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { goalId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetGoal, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getGoal(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
