/**
 * DeclineRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: proposals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DeclineRepository Port
 *
 * DDD: Application port for declinerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { DeclineActionProposalInput, DeclineActionProposalOutput } from "../dto/decline.dto";
export interface DeclineRepository {
  declineActionProposal(input: DeclineActionProposalInput): Promise<DeclineActionProposalOutput>;
}

export type { DeclineActionProposalInput, DeclineActionProposalOutput } from "../dto/decline.dto";
