/**
 * Main Services Package Index
 *
 * Generated by Services Main Index Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Services Package - Main Barrel Export
 *
 * Central export point for all application services (use cases, ports, DTOs, policies, errors)
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended)
 *   import { activity, ai, conversation } from "@autara/services";
 *   const { usecases, dto, ports } = activity;
 *
 *   // Direct imports from domain
 *   import { ExecuteCreateEventUseCase } from "@autara/services/activity";
 *   
 *   // Shared services
 *   import { executionContextService } from "@autara/services";
 */

// ============================================================================
// SHARED SERVICES EXPORTS
// ============================================================================
export { executionContextService } from "./_shared/index.js";

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types across domains

import * as _accounts from "./accounts/index.js";
import * as _actions from "./actions/index.js";
import * as _complaints from "./complaints/index.js";
import * as _explanations from "./explanations/index.js";
import * as _goals from "./goals/index.js";
import * as _governance from "./governance/index.js";
import * as _identity from "./identity/index.js";
import * as _outcomes from "./outcomes/index.js";
import * as _proposals from "./proposals/index.js";

// Export as namespaces
export const accounts = _accounts;
export const actions = _actions;
export const complaints = _complaints;
export const explanations = _explanations;
export const goals = _goals;
export const governance = _governance;
export const identity = _identity;
export const outcomes = _outcomes;
export const proposals = _proposals;
