/**
 * ExecuteGetComplaintCase - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: complaints
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetComplaintCase Use Case
 *
 * DDD: Application use case for get Complaint.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetComplaintCaseInput, GetComplaintCaseOutput } from "../dto/complaint.dto";
import type { ExecutionContextService, IdGeneratorService } from "@autara/services/_shared/index.js";
import type { ComplaintRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetComplaintCase {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly complaint: ComplaintRepository
  ) {}

  async execute(input: GetComplaintCaseInput): Promise<GetComplaintCaseOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.cmpId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).complaintId) {
      throw new ValidationError("complaintId is required");
    }
    const complaintId = (input as any).complaintId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.complaint.getComplaintCase({ complaintId: complaintId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${complaintId}`);
    }

    return entity as GetComplaintCaseOutput;
  }
}
