/**
 * ExecuteGetGoal - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: goals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetGoal Use Case
 *
 * DDD: Application use case for get Goal.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetGoalInput, GetGoalOutput } from "../dto/goal.dto";
import type { ExecutionContextService, IdGeneratorService } from "@autara/services/_shared/index.js";
import type { GoalRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetGoal {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly goal: GoalRepository
  ) {}

  async execute(input: GetGoalInput): Promise<GetGoalOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.golId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).customerId) {
      throw new ValidationError("customerId is required");
    }
    const customerId = (input as any).customerId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.goal.getGoal({ customerId: customerId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${customerId}`);
    }

    return entity as GetGoalOutput;
  }
}
