/**
 * ExecuteListGoals - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: goals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListGoals Use Case
 *
 * DDD: Application use case for list Goal.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListGoalsInput, ListGoalsOutput } from "../dto/goal.dto";
import type { ExecutionContextService, IdGeneratorService } from "@autara/services/_shared/index.js";
import type { GoalRepository } from "../ports";

export class ExecuteListGoals {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly goal: GoalRepository
  ) {}

  async execute(input: ListGoalsInput): Promise<ListGoalsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.golId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.goal.listGoals({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListGoalsOutput;
  }
}
