/**
 * ExecuteCreateGoal - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: goals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateGoal Use Case
 *
 * DDD: Application use case for create Goal.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateGoalInput, CreateGoalOutput } from "../dto/goal.dto";
import type { ExecutionContextService, IdGeneratorService } from "@autara/services/_shared/index.js";
import type { GoalRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateGoal {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly goal: GoalRepository
  ) {}

  async execute(input: CreateGoalInput): Promise<CreateGoalOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.golId();

    // All field names extracted from OpenAPI spec: currency, targetAmount, type
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.targetAmount) {
      throw new ValidationError("targetAmount is required");
    }
    if (!input.type) {
      throw new ValidationError("type is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (goals domain)
    const entityId = this.idGenerator.golId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.goal.createGoal({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateGoalOutput;
  }
}
