/**
 * ExecuteListConstraints - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: goals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListConstraints Use Case
 *
 * DDD: Application use case for list Constraint.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListConstraintsInput, ListConstraintsOutput } from "../dto/constraint.dto";
import type { ExecutionContextService, IdGeneratorService } from "@autara/services/_shared/index.js";
import type { ConstraintRepository } from "../ports";

export class ExecuteListConstraints {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly constraint: ConstraintRepository
  ) {}

  async execute(input: ListConstraintsInput): Promise<ListConstraintsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.golId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.constraint.listConstraints({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListConstraintsOutput;
  }
}
