/**
 * Handlers index
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./approve.handlers.js";
export * from "./fairness.handlers.js";
export * from "./kill-switch.handlers.js";
export * from "./model-version.handlers.js";
export * from "./rollback.handlers.js";
export * from "./vendor.handlers.js";
