/**
 * Routes for Approve
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { approveModelVersion } from "../handlers/approve.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function approveRoutes(fastify: FastifyInstance) {
  // POST /v1/governance/model-versions/{modelVersionId}/approve (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/governance/model-versions/:modelVersionId/approve",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { modelVersionId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getGovernanceDependenciesForRequest();
        await approveModelVersion(request, reply, deps);
      });
    }
  );


}
