/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { fairnessRoutes } from "./fairness.routes.js";
export { modelVersionRoutes } from "./model-version.routes.js";
export { vendorRoutes } from "./vendor.routes.js";
export { approveRoutes } from "./approve.routes.js";
export { killSwitchRoutes } from "./kill-switch.routes.js";
export { rollbackRoutes } from "./rollback.routes.js";
