/**
 * Goal Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: goals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { GoalEntity } from "@autara/core/goals/models/index.js";
import { goalsSchemas } from "@autara/core/goals";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "gol";

export function createGoal(overrides: Partial<GoalEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    customerId: overrides.customerId ?? `cst_${ulid().toLowerCase()}`,
    goalId: overrides.goalId ?? `gol_${ulid().toLowerCase()}`,
    status: overrides.status ?? "active",
    targetAmount: overrides.targetAmount ?? faker.number.int(),
    type: overrides.type ?? "emergencyBuffer",
    ...overrides,
  };

  return goalsSchemas.Goal.parse(raw);
}

export function goalBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createGoal(overrides));
}
