/**
 * ExecuteGetExplanationRecord - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: explanations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetExplanationRecord Use Case
 *
 * DDD: Application use case for get Explanation.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetExplanationRecordInput, GetExplanationRecordOutput } from "../dto/explanation.dto";
import type { ExecutionContextService, IdGeneratorService } from "@autara/services/_shared/index.js";
import type { ExplanationRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetExplanationRecord {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly explanation: ExplanationRepository
  ) {}

  async execute(input: GetExplanationRecordInput): Promise<GetExplanationRecordOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.xplId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).explanationId) {
      throw new ValidationError("explanationId is required");
    }
    const explanationId = (input as any).explanationId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.explanation.getExplanationRecord({ explanationId: explanationId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${explanationId}`);
    }

    return entity as GetExplanationRecordOutput;
  }
}
