/**
 * OutcomeRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: outcomes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * OutcomeRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements OutcomeRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  OutcomeRepository,
} from "@autara/services/outcomes";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { OutcomeRepositoryDdb } from "./outcome-repository.ddb.js";

/**
 * OutcomeRepositoryAdapter
 *
 * Implements OutcomeRepository port for infrastructure layer.
 */
export class OutcomeRepositoryAdapter implements OutcomeRepository {
  private readonly ddb: OutcomeRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new OutcomeRepositoryDdb(this.dynamoClient);
  }

  async getOutcomeReport(input: Parameters<OutcomeRepository['getOutcomeReport']>[0]): Promise<Awaited<ReturnType<OutcomeRepository['getOutcomeReport']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getOutcomeReport(input);
  }
}
