/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: actions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { actionRoutes } from "./action.routes.js";
export { automationRoutes } from "./automation.routes.js";
export { pauseRoutes } from "./pause.routes.js";
export { resumeRoutes } from "./resume.routes.js";
export { reverseRoutes } from "./reverse.routes.js";
