/**
 * Constraint DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: goals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Constraint DTOs
 *
 * DDD: Application DTOs for Constraint use cases.
 */

import type { CreateConstraintParams, CreateConstraintRequestInput, ListConstraintsParams } from "@autara/core/goals/types";

export type ListConstraintsInput = ListConstraintsParams;

export type CreateConstraintInput = CreateConstraintParams & CreateConstraintRequestInput;

export type ListConstraintsOutput = {};

export type CreateConstraintOutput = {};
