/**
 * ExecuteGetExecutedAction - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: actions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetExecutedAction Use Case
 *
 * DDD: Application use case for get Action.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetExecutedActionInput, GetExecutedActionOutput } from "../dto/action.dto";
import type { ExecutionContextService, IdGeneratorService } from "@autara/services/_shared/index.js";
import type { ActionRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetExecutedAction {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly action: ActionRepository
  ) {}

  async execute(input: GetExecutedActionInput): Promise<GetExecutedActionOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.actId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).actionId) {
      throw new ValidationError("actionId is required");
    }
    const actionId = (input as any).actionId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.action.getExecutedAction({ actionId: actionId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${actionId}`);
    }

    return entity as GetExecutedActionOutput;
  }
}
