/**
 * ExecuteGetOutcomeReport - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: outcomes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetOutcomeReport Use Case
 *
 * DDD: Application use case for get Outcome.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetOutcomeReportInput, GetOutcomeReportOutput } from "../dto/outcome.dto";
import type { ExecutionContextService, IdGeneratorService } from "@autara/services/_shared/index.js";
import type { OutcomeRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetOutcomeReport {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly outcome: OutcomeRepository
  ) {}

  async execute(input: GetOutcomeReportInput): Promise<GetOutcomeReportOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.outId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).customerId) {
      throw new ValidationError("customerId is required");
    }
    const customerId = (input as any).customerId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.outcome.getOutcomeReport({ customerId: customerId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${customerId}`);
    }

    return entity as GetOutcomeReportOutput;
  }
}
