/**
 * FairnessRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * FairnessRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements FairnessRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  FairnessRepository,
} from "@autara/services/governance";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { FairnessRepositoryDdb } from "./fairness-repository.ddb.js";

/**
 * FairnessRepositoryAdapter
 *
 * Implements FairnessRepository port for infrastructure layer.
 */
export class FairnessRepositoryAdapter implements FairnessRepository {
  private readonly ddb: FairnessRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new FairnessRepositoryDdb(this.dynamoClient);
  }

  async getFairnessMonitoring(input: Parameters<FairnessRepository['getFairnessMonitoring']>[0]): Promise<Awaited<ReturnType<FairnessRepository['getFairnessMonitoring']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getFairnessMonitoring(input);
  }
}
