/**
 * VendorRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * VendorRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements VendorRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  VendorRepository,
} from "@autara/services/governance";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { VendorRepositoryDdb } from "./vendor-repository.ddb.js";

/**
 * VendorRepositoryAdapter
 *
 * Implements VendorRepository port for infrastructure layer.
 */
export class VendorRepositoryAdapter implements VendorRepository {
  private readonly ddb: VendorRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new VendorRepositoryDdb(this.dynamoClient);
  }

  async listVendorDependencies(input: Parameters<VendorRepository['listVendorDependencies']>[0]): Promise<Awaited<ReturnType<VendorRepository['listVendorDependencies']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listVendorDependencies(input);
  }
}
