/**
 * GetAccount DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: accounts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetFinancialAccountParams } from "@autara/core/accounts";

export function createGetAccountRequest(overrides: Partial<GetFinancialAccountParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
