/**
 * Proposals DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: proposals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Proposals Domain Module - Composition root
 *
 * DDD: Composition root for proposals domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ConfirmRepositoryAdapter,
  DeclineRepositoryAdapter,
  ExceptionQueueRepositoryAdapter,
  ProposalRepositoryAdapter,
} from "@autara/adapters/proposals";
import { getIdGeneratorService } from "@autara/adapters";
import type { AdapterDynamoDBClient } from "@autara/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteConfirmActionProposal,
  ExecuteCreateActionProposal,
  ExecuteDeclineActionProposal,
  ExecuteGetActionProposal,
  ExecuteListActionProposals,
  ExecuteListAdviserExceptions,
} from "@autara/services/proposals/usecases";
// Ports (interfaces)
import type {
  ConfirmRepository,
  DeclineRepository,
  ExceptionQueueRepository,
  ProposalRepository,
} from "@autara/services/proposals/ports";

export interface ProposalsDomainModule {
  repos: {
    confirms: ConfirmRepository;
    declines: DeclineRepository;
    exceptionQueues: ExceptionQueueRepository;
    proposals: ProposalRepository;
  };
  useCases: {
    confirms: {
      get: ExecuteConfirmActionProposal;
    };
    declines: {
      get: ExecuteDeclineActionProposal;
    };
    exceptionQueues: {
      list: ExecuteListAdviserExceptions;
    };
    proposals: {
      create: ExecuteCreateActionProposal;
      get: ExecuteGetActionProposal;
      list: ExecuteListActionProposals;
    };
  };
}

export function buildProposalsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): ProposalsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      confirms?: ConfirmRepository;
      declines?: DeclineRepository;
      exceptionQueues?: ExceptionQueueRepository;
      proposals?: ProposalRepository;
    } = {};

    obj.confirms = new ConfirmRepositoryAdapter(dynamoClient);
    obj.declines = new DeclineRepositoryAdapter(dynamoClient);
    obj.exceptionQueues = new ExceptionQueueRepositoryAdapter(dynamoClient);
    obj.proposals = new ProposalRepositoryAdapter(dynamoClient);
    return {
      confirms: obj.confirms!,
      declines: obj.declines!,
      exceptionQueues: obj.exceptionQueues!,
      proposals: obj.proposals!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    confirms: {
      get: new ExecuteConfirmActionProposal(executionContext, idGenerator, repos.confirms),
    },
    declines: {
      get: new ExecuteDeclineActionProposal(executionContext, idGenerator, repos.declines),
    },
    exceptionQueues: {
      list: new ExecuteListAdviserExceptions(executionContext, idGenerator, repos.exceptionQueues),
    },
    proposals: {
      create: new ExecuteCreateActionProposal(executionContext, idGenerator, repos.proposals),
      get: new ExecuteGetActionProposal(executionContext, idGenerator, repos.proposals),
      list: new ExecuteListActionProposals(executionContext, idGenerator, repos.proposals),
    },
  };
  return { repos, useCases: useCases as ProposalsDomainModule["useCases"] };
}
