/**
 * Explanations DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: explanations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Explanations Domain Module - Composition root
 *
 * DDD: Composition root for explanations domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ExplanationRepositoryAdapter,
} from "@autara/adapters/explanations";
import { getIdGeneratorService } from "@autara/adapters";
import type { AdapterDynamoDBClient } from "@autara/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetExplanationRecord,
  ExecuteListExplanationRecords,
} from "@autara/services/explanations/usecases";
// Ports (interfaces)
import type {
  ExplanationRepository,
} from "@autara/services/explanations/ports";

export interface ExplanationsDomainModule {
  repos: {
    explanations: ExplanationRepository;
  };
  useCases: {
    explanations: {
      get: ExecuteGetExplanationRecord;
      list: ExecuteListExplanationRecords;
    };
  };
}

export function buildExplanationsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): ExplanationsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      explanations?: ExplanationRepository;
    } = {};

    obj.explanations = new ExplanationRepositoryAdapter(dynamoClient);
    return {
      explanations: obj.explanations!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    explanations: {
      get: new ExecuteGetExplanationRecord(executionContext, idGenerator, repos.explanations),
      list: new ExecuteListExplanationRecords(executionContext, idGenerator, repos.explanations),
    },
  };
  return { repos, useCases: useCases as ExplanationsDomainModule["useCases"] };
}
